---
# defaults file for required_apps
- hosts: localhost
  become: true
  connection: local
  vars_files: 
  - vars/main.yml

  pre_tasks:
  - name: update repos.
    ansible.builtin.package:
      update_cache: yes
    changed_when: false
  - name: Install_packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: latest
    loop: "{{ package_lists }}"

  tasks:
    - import_tasks: tasks/users.yml  
    - import_tasks: tasks/cron.yml  
    - import_tasks: tasks/packages.yml  
