- name: add ansible-pull cron job
  cron:
    name: Ansible auto-provision
    user: senseble
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/PratikMoitra/ansible-files.git playbook.yml > /dev/null"

